# Generated by Django 3.1.4 on 2020-12-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_auto_20201228_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='doenca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sintomas', models.CharField(max_length=100)),
            ],
        ),
    ]
