# Generated by Django 3.1.4 on 2020-12-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_doenca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epidemiologico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_coleta', models.CharField(max_length=10)),
                ('doenca_associada', models.CharField(max_length=100)),
            ],
        ),
    ]
